-- SAGC · Esquema oficial para Supabase / PostgreSQL
-- Ejecutar en Supabase Dashboard > SQL Editor sobre un proyecto nuevo.
-- PostgreSQL
--
-- Arquitectura:
-- React/Vite -> Express API -> Supabase Data API -> PostgreSQL
--
-- Las claves secretas de Supabase pertenecen exclusivamente al backend.
-- El frontend no accede directamente a estas tablas.

begin;

-- ---------------------------------------------------------------------
-- Utilidad para fecha_actualizacion
-- ---------------------------------------------------------------------

create or replace function public.sagc_set_fecha_actualizacion()
returns trigger
language plpgsql
as $$
begin
  new.fecha_actualizacion = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- 1. USUARIOS
-- ---------------------------------------------------------------------

create table if not exists public.usuarios (
  id_usuario bigint generated by default as identity primary key,
  nombre varchar(180) not null,
  usuario varchar(100) not null unique,
  password_hash varchar(255) not null,
  permiso varchar(10) not null default 'NORMAL'
    check (permiso in ('NORMAL', 'ADMIN')),
  foto_url text,
  activo boolean not null default true,
  fecha_creacion timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create index if not exists idx_usuarios_activo
  on public.usuarios (activo);

create index if not exists idx_usuarios_permiso
  on public.usuarios (permiso);

drop trigger if exists trg_usuarios_fecha_actualizacion on public.usuarios;
create trigger trg_usuarios_fecha_actualizacion
before update on public.usuarios
for each row execute function public.sagc_set_fecha_actualizacion();

-- ---------------------------------------------------------------------
-- 2. TIPOS DE DOCUMENTO
-- ---------------------------------------------------------------------

create table if not exists public.tipos_documento (
  id_tipo_documento bigint generated by default as identity primary key,
  clave varchar(50) not null unique,
  nombre varchar(120) not null unique,
  activo boolean not null default true,
  fecha_creacion timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

drop trigger if exists trg_tipos_documento_fecha_actualizacion
  on public.tipos_documento;
create trigger trg_tipos_documento_fecha_actualizacion
before update on public.tipos_documento
for each row execute function public.sagc_set_fecha_actualizacion();

-- ---------------------------------------------------------------------
-- 3. EVENTOS
-- ---------------------------------------------------------------------

create table if not exists public.eventos (
  id_evento bigint generated by default as identity primary key,
  codigo varchar(80) not null unique,
  nombre varchar(255) not null,
  lugar varchar(255),
  fecha_inicio date,
  fecha_fin date,
  creado_por bigint references public.usuarios(id_usuario)
    on update cascade on delete set null,
  id_responsable bigint references public.usuarios(id_usuario)
    on update cascade on delete set null,
  estado varchar(12) not null default 'BORRADOR'
    check (estado in ('BORRADOR', 'ACTIVO', 'CERRADO', 'CANCELADO')),
  fecha_creacion timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now(),
  check (fecha_fin is null or fecha_inicio is null or fecha_fin >= fecha_inicio)
);

create index if not exists idx_eventos_estado
  on public.eventos (estado);

create index if not exists idx_eventos_creado_por
  on public.eventos (creado_por);

create index if not exists idx_eventos_responsable
  on public.eventos (id_responsable);

drop trigger if exists trg_eventos_fecha_actualizacion on public.eventos;
create trigger trg_eventos_fecha_actualizacion
before update on public.eventos
for each row execute function public.sagc_set_fecha_actualizacion();

-- ---------------------------------------------------------------------
-- 4. TEXTOS DEL EVENTO
-- ---------------------------------------------------------------------

create table if not exists public.textos_evento (
  id_texto bigint generated by default as identity primary key,
  id_evento bigint not null references public.eventos(id_evento)
    on update cascade on delete cascade,
  encabezado varchar(255) not null,
  otorga varchar(100),
  tipo varchar(100) not null,
  cuerpo text,
  lugar_fecha varchar(255),
  configuracion jsonb,
  fecha_creacion timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now()
);

create index if not exists idx_textos_evento
  on public.textos_evento (id_evento);

drop trigger if exists trg_textos_evento_fecha_actualizacion
  on public.textos_evento;
create trigger trg_textos_evento_fecha_actualizacion
before update on public.textos_evento
for each row execute function public.sagc_set_fecha_actualizacion();

-- ---------------------------------------------------------------------
-- 5. CAMPOS PERSONALIZADOS DEL EVENTO
-- ---------------------------------------------------------------------

create table if not exists public.campos_evento (
  id_campo bigint generated by default as identity primary key,
  id_evento bigint not null references public.eventos(id_evento)
    on update cascade on delete cascade,
  clave varchar(80) not null,
  etiqueta varchar(150) not null,
  tipo varchar(20) not null default 'TEXTO'
    check (tipo in ('TEXTO', 'TEXTO_LARGO', 'NUMERO', 'FECHA', 'BOOLEANO')),
  requerido boolean not null default false,
  orden integer not null default 0 check (orden >= 0),
  fecha_creacion timestamptz not null default now(),
  unique (id_evento, clave)
);

create index if not exists idx_campos_evento_orden
  on public.campos_evento (id_evento, orden);

-- ---------------------------------------------------------------------
-- 6. PLANTILLAS
-- ---------------------------------------------------------------------

create table if not exists public.plantillas (
  id_plantilla bigint generated by default as identity primary key,
  id_tipo_documento bigint references public.tipos_documento(id_tipo_documento)
    on update cascade on delete set null,
  nombre varchar(180) not null,
  version integer not null default 1 check (version >= 1),
  modo varchar(12) not null default 'REUTILIZABLE'
    check (modo in ('TEMPORAL', 'REUTILIZABLE')),
  archivo_url text not null,
  miniatura_url text,
  mime_type varchar(100),
  ancho_px integer check (ancho_px is null or ancho_px > 0),
  alto_px integer check (alto_px is null or alto_px > 0),
  orientacion varchar(10) not null
    check (orientacion in ('VERTICAL', 'HORIZONTAL')),
  tamano varchar(50) not null,
  creado_por bigint references public.usuarios(id_usuario)
    on update cascade on delete set null,
  activo boolean not null default true,
  fecha_creacion timestamptz not null default now(),
  fecha_actualizacion timestamptz not null default now(),
  unique (nombre, version)
);

create index if not exists idx_plantillas_tipo_activo
  on public.plantillas (id_tipo_documento, activo);

create index if not exists idx_plantillas_creado_por
  on public.plantillas (creado_por);

drop trigger if exists trg_plantillas_fecha_actualizacion
  on public.plantillas;
create trigger trg_plantillas_fecha_actualizacion
before update on public.plantillas
for each row execute function public.sagc_set_fecha_actualizacion();

-- ---------------------------------------------------------------------
-- 7. CONTADOR DE FOLIOS
-- Folio Único SAGC V1: AAAA-X-XXXX
-- ---------------------------------------------------------------------

create table if not exists public.contador_folios (
  anio smallint primary key
    check (anio between 1000 and 9999),
  serie char(1) not null default 'A'
    check (serie between 'A' and 'Z'),
  ultimo_valor smallint not null default 0
    check (ultimo_valor between 0 and 9999),
  fecha_actualizacion timestamptz not null default now()
);

drop trigger if exists trg_contador_folios_fecha_actualizacion
  on public.contador_folios;
create trigger trg_contador_folios_fecha_actualizacion
before update on public.contador_folios
for each row execute function public.sagc_set_fecha_actualizacion();

-- Reserva atómica del siguiente folio.
-- Una llamada RPC se ejecuta dentro de una transacción PostgreSQL.
create or replace function public.asignar_siguiente_folio(
  p_fecha_emision date
)
returns text
language plpgsql
set search_path = public
as $$
declare
  v_anio smallint;
  v_serie char(1);
  v_ultimo smallint;
  v_siguiente smallint;
begin
  if p_fecha_emision is null then
    raise exception 'FECHA_EMISION_REQUERIDA';
  end if;

  v_anio := extract(year from p_fecha_emision)::smallint;

  insert into public.contador_folios (anio, serie, ultimo_valor)
  values (v_anio, 'A', 0)
  on conflict (anio) do nothing;

  select serie, ultimo_valor
    into v_serie, v_ultimo
  from public.contador_folios
  where anio = v_anio
  for update;

  if v_ultimo < 9999 then
    v_siguiente := v_ultimo + 1;
  else
    if v_serie = 'Z' then
      raise exception 'FOLIOS_AGOTADOS:%', v_anio;
    end if;

    v_serie := chr(ascii(v_serie) + 1);
    v_siguiente := 1;
  end if;

  update public.contador_folios
  set
    serie = v_serie,
    ultimo_valor = v_siguiente
  where anio = v_anio;

  return concat(
    v_anio::text,
    '-',
    v_serie,
    '-',
    lpad(v_siguiente::text, 4, '0')
  );
end;
$$;

-- ---------------------------------------------------------------------
-- 8. CONSTANCIAS
-- ---------------------------------------------------------------------

create table if not exists public.constancias (
  id_constancia bigint generated by default as identity primary key,
  id_evento bigint not null references public.eventos(id_evento)
    on update cascade on delete restrict,
  id_tipo_documento bigint not null references public.tipos_documento(id_tipo_documento)
    on update cascade on delete restrict,
  id_plantilla bigint references public.plantillas(id_plantilla)
    on update cascade on delete set null,
  nombre_persona varchar(220) not null,
  datos_variables jsonb,
  folio varchar(11) not null unique
    check (folio ~ '^[0-9]{4}-[A-Z]-[0-9]{4}$')
    check (right(folio, 4)::integer between 1 and 9999),
  -- Token Único SAGC V1 · UUID versión 4 (RFC 9562)
  token_unico uuid not null unique,
  cadena_validacion text not null,
  qr_destino text not null,
  fecha_emision timestamptz not null default now(),
  emitido_por bigint not null references public.usuarios(id_usuario)
    on update cascade on delete restrict,
  estado varchar(12) not null default 'EMITIDA'
    check (estado in ('EMITIDA', 'CANCELADA', 'REEXPEDIDA')),
  id_constancia_origen bigint references public.constancias(id_constancia)
    on update cascade on delete set null,
  motivo_cancelacion varchar(500),
  fecha_cancelacion timestamptz,
  fecha_actualizacion timestamptz not null default now()
);

create index if not exists idx_constancias_evento
  on public.constancias (id_evento);

create index if not exists idx_constancias_tipo
  on public.constancias (id_tipo_documento);

create index if not exists idx_constancias_plantilla
  on public.constancias (id_plantilla);

create index if not exists idx_constancias_nombre
  on public.constancias (nombre_persona);

create index if not exists idx_constancias_estado
  on public.constancias (estado);

create index if not exists idx_constancias_fecha
  on public.constancias (fecha_emision);

create index if not exists idx_constancias_emisor
  on public.constancias (emitido_por);

drop trigger if exists trg_constancias_fecha_actualizacion on public.constancias;
create trigger trg_constancias_fecha_actualizacion
before update on public.constancias
for each row execute function public.sagc_set_fecha_actualizacion();

-- ---------------------------------------------------------------------
-- 9. AUDITORÍA
-- ---------------------------------------------------------------------

create table if not exists public.auditoria (
  id_auditoria bigint generated by default as identity primary key,
  id_usuario bigint references public.usuarios(id_usuario)
    on update cascade on delete set null,
  accion varchar(100) not null,
  entidad varchar(80) not null,
  id_entidad bigint,
  ip inet,
  metadata jsonb,
  fecha timestamptz not null default now()
);

create index if not exists idx_auditoria_usuario_fecha
  on public.auditoria (id_usuario, fecha);

create index if not exists idx_auditoria_entidad
  on public.auditoria (entidad, id_entidad);

-- ---------------------------------------------------------------------
-- 10. HEALTH CHECK PARA LA API
-- ---------------------------------------------------------------------

create or replace function public.sagc_healthcheck()
returns jsonb
language sql
stable
set search_path = public
as $$
  select jsonb_build_object(
    'provider', 'Supabase',
    'database', 'PostgreSQL',
    'schema', current_schema(),
    'server_time', now()
  );
$$;

-- ---------------------------------------------------------------------
-- 11. SEGURIDAD SUPABASE
-- ---------------------------------------------------------------------
-- SAGC accede a las tablas exclusivamente desde su backend Express
-- usando una clave secreta de Supabase. No se habilita acceso directo
-- anon/authenticated por Data API en esta etapa.

alter table public.usuarios enable row level security;
alter table public.tipos_documento enable row level security;
alter table public.eventos enable row level security;
alter table public.textos_evento enable row level security;
alter table public.campos_evento enable row level security;
alter table public.plantillas enable row level security;
alter table public.contador_folios enable row level security;
alter table public.constancias enable row level security;
alter table public.auditoria enable row level security;

revoke all on table
  public.usuarios,
  public.tipos_documento,
  public.eventos,
  public.textos_evento,
  public.campos_evento,
  public.plantillas,
  public.contador_folios,
  public.constancias,
  public.auditoria
from anon, authenticated;

grant select, insert, update, delete on table
  public.usuarios,
  public.tipos_documento,
  public.eventos,
  public.textos_evento,
  public.campos_evento,
  public.plantillas,
  public.contador_folios,
  public.constancias,
  public.auditoria
to service_role;

grant usage, select on all sequences in schema public to service_role;

revoke execute on function public.asignar_siguiente_folio(date)
  from public, anon, authenticated;
grant execute on function public.asignar_siguiente_folio(date)
  to service_role;

revoke execute on function public.sagc_healthcheck()
  from public, anon, authenticated;
grant execute on function public.sagc_healthcheck()
  to service_role;

commit;